"""initial schema

Revision ID: 9791a814c040
Revises: 
Create Date: 2026-03-13 23:28:55.492056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9791a814c040'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('broker_or_bank', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assets',
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('asset_class', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('isin', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('target_min', sa.Float(), nullable=True),
    sa.Column('target_max', sa.Float(), nullable=True),
    sa.Column('target_pct', sa.Float(), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('ticker')
    )
    op.create_table('asset_valuations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('nominal_value', sa.Float(), nullable=True),
    sa.Column('nominal_currency', sa.String(), nullable=True),
    sa.Column('value_pct', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['ticker'], ['assets.ticker'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'ticker', name='uq_valuation_date_ticker')
    )
    op.create_table('bond_info',
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('face_value', sa.Float(), nullable=False),
    sa.Column('base_currency', sa.String(), nullable=True),
    sa.Column('coupon_rate', sa.Float(), nullable=True),
    sa.Column('coupon_sum', sa.Float(), nullable=True),
    sa.Column('coupon_currency', sa.String(), nullable=True),
    sa.Column('coupon_frequency_year', sa.Integer(), nullable=True),
    sa.Column('coupon_frequency_day', sa.Integer(), nullable=True),
    sa.Column('maturity_date', sa.Date(), nullable=True),
    sa.Column('offer_date', sa.Date(), nullable=True),
    sa.Column('first_coupon_date', sa.Date(), nullable=True),
    sa.Column('is_amortizing', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ticker'], ['assets.ticker'], ),
    sa.PrimaryKeyConstraint('ticker')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('tx_type', sa.String(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('nominal_amount', sa.Float(), nullable=True),
    sa.Column('nominal_currency', sa.String(), nullable=True),
    sa.Column('nkd', sa.Float(), nullable=True),
    sa.Column('commission', sa.Float(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('broker', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['ticker'], ['assets.ticker'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('bond_info')
    op.drop_table('asset_valuations')
    op.drop_table('assets')
    op.drop_table('accounts')
    # ### end Alembic commands ###
