"""add_currencies_table

Revision ID: ad8a3604e110
Revises: 9bb0d8f46eb6
Create Date: 2026-03-14 22:28:21.981369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad8a3604e110'
down_revision: Union[str, Sequence[str], None] = '9bb0d8f46eb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    currencies_table = op.create_table('currencies',
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(length=4), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.bulk_insert(currencies_table, [
        {"code": "USD", "name": "Доллар США", "symbol": "$"},
        {"code": "EUR", "name": "Евро", "symbol": "€"},
        {"code": "CNY", "name": "Юань", "symbol": "¥"},
    ])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('currencies')
    # ### end Alembic commands ###
